create table tb_article (author_id bigint, id bigserial not null, content text, title varchar(255), url_photo varchar(255), primary key (id));
create table tb_city (id bigserial not null, state_id bigint, name varchar(255), primary key (id));
create table tb_media (id bigserial not null, url varchar(255), primary key (id));
create table tb_role (id bigserial not null, authority varchar(255), primary key (id));
create table tb_state (id bigserial not null, name varchar(255) unique, primary key (id));
create table tb_tutorial (author_id bigint, id bigserial not null, content text, title varchar(255), primary key (id));
create table tb_tutorial_media (media_id bigint not null, tutorial_id bigint not null, primary key (media_id, tutorial_id));
create table tb_user (birth_day date, city_id bigint, id bigserial not null, state_id bigint, bio varchar(255), email varchar(255), gender varchar(255) check (gender in ('MALE','FEMALE','OTHERS')), name varchar(255), password varchar(255), phone varchar(255), url_photo varchar(255), primary key (id));
create table tb_user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));
alter table if exists tb_article add constraint FKi2770gm5tf8ghdmv8cqvlh2lk foreign key (author_id) references tb_user;
alter table if exists tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state;
alter table if exists tb_tutorial add constraint FKrk2cdvqdg2q5k797rya3h7mpm foreign key (author_id) references tb_user;
alter table if exists tb_tutorial_media add constraint FKg6pljbcmdm4scsry1u86lyswq foreign key (media_id) references tb_media;
alter table if exists tb_tutorial_media add constraint FK95rvnpl63nlvkhkdvgujy2dem foreign key (tutorial_id) references tb_tutorial;
alter table if exists tb_user add constraint FKinhks6mglno4yyrtj72ad3evj foreign key (city_id) references tb_city;
alter table if exists tb_user add constraint FKc6p1rfmndjmco6f9kaghn5ewh foreign key (state_id) references tb_state;
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_state(name) VALUES('pernambuco');
INSERT INTO tb_city(name, state_id) VALUES('recife', 1);
INSERT INTO tb_city(name, state_id) VALUES('jaboatão dos Guararapes', 1);
INSERT INTO tb_city(name, state_id) VALUES('olinda', 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('NaveGuard', 'navguard@navguard.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81987654321', '1998-05-15', 'https://example.com/photos/ana.jpg', 'FEMALE', 'Apaixonada por tecnologia e viagens.', 1, 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('Carlos Eduardo', 'carlos.edu@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81999887766', '1995-11-20', 'https://example.com/photos/carlos.jpg', 'MALE', 'Engenheiro de software com interesse em IA e startups.', 1, 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('Mariana Souza', 'mariana.souza@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81991234567', '2000-07-08', 'https://example.com/photos/mariana.jpg', 'FEMALE', 'Designer apaixonada por criar experiências visuais incríveis.', 1, 1);
INSERT INTO tb_role(authority) VALUES ('ROLE_CLIENT');
INSERT INTO tb_role(authority) VALUES ('ROLE_ADMIN');
insert into tb_user_role(user_id, role_id) VALUES(1,1);
insert into tb_user_role(user_id, role_id) VALUES(1,2);
insert into tb_user_role(user_id, role_id) VALUES(2,1);
insert into tb_user_role(user_id, role_id) VALUES(3,1);
INSERT INTO tb_article(title, content, url_photo, author_id) VALUES ('Segurança crianças', 'Crianças não devem usar internet sem um adulto', 'htto', 1);
INSERT INTO tb_article(title, content, url_photo, author_id) VALUES ('Segurança adolescente', 'Adolescentes não devem usar internet sem um adulto', 'htto', 2);
INSERT INTO tb_tutorial(title, content, author_id) VALUES('Jogos digitais', 'Jogos podem ser prejudicias as crianças', 1);
INSERT INTO tb_tutorial(title, content, author_id) VALUES('Cassinos digitais', 'Cassinos podem ser prejudicias as crianças', 2);
INSERT INTO tb_media(url) VALUES('https');
INSERT INTO tb_media(url) VALUES('http');
INSERT INTO tb_tutorial_media(tutorial_id, media_id) VALUES (1, 1);
INSERT INTO tb_tutorial_media(tutorial_id, media_id) VALUES (2, 2);
create table tb_article (author_id bigint, id bigserial not null, content text, title varchar(255), url_photo varchar(255), primary key (id));
create table tb_city (id bigserial not null, state_id bigint, name varchar(255), primary key (id));
create table tb_media (id bigserial not null, url varchar(255), primary key (id));
create table tb_role (id bigserial not null, authority varchar(255), primary key (id));
create table tb_state (id bigserial not null, name varchar(255) unique, primary key (id));
create table tb_tutorial (author_id bigint, id bigserial not null, content text, title varchar(255), primary key (id));
create table tb_tutorial_media (media_id bigint not null, tutorial_id bigint not null, primary key (media_id, tutorial_id));
create table tb_user (birth_day date, city_id bigint, id bigserial not null, state_id bigint, bio varchar(255), email varchar(255), gender varchar(255) check (gender in ('MALE','FEMALE','OTHERS')), name varchar(255), password varchar(255), phone varchar(255), url_photo varchar(255), primary key (id));
create table tb_user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));
alter table if exists tb_article add constraint FKi2770gm5tf8ghdmv8cqvlh2lk foreign key (author_id) references tb_user;
alter table if exists tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state;
alter table if exists tb_tutorial add constraint FKrk2cdvqdg2q5k797rya3h7mpm foreign key (author_id) references tb_user;
alter table if exists tb_tutorial_media add constraint FKg6pljbcmdm4scsry1u86lyswq foreign key (media_id) references tb_media;
alter table if exists tb_tutorial_media add constraint FK95rvnpl63nlvkhkdvgujy2dem foreign key (tutorial_id) references tb_tutorial;
alter table if exists tb_user add constraint FKinhks6mglno4yyrtj72ad3evj foreign key (city_id) references tb_city;
alter table if exists tb_user add constraint FKc6p1rfmndjmco6f9kaghn5ewh foreign key (state_id) references tb_state;
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_state(name) VALUES('pernambuco');
INSERT INTO tb_city(name, state_id) VALUES('recife', 1);
INSERT INTO tb_city(name, state_id) VALUES('jaboatão dos Guararapes', 1);
INSERT INTO tb_city(name, state_id) VALUES('olinda', 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('NaveGuard', 'navguard@navguard.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81987654321', '1998-05-15', 'https://example.com/photos/ana.jpg', 'FEMALE', 'Apaixonada por tecnologia e viagens.', 1, 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('Carlos Eduardo', 'carlos.edu@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81999887766', '1995-11-20', 'https://example.com/photos/carlos.jpg', 'MALE', 'Engenheiro de software com interesse em IA e startups.', 1, 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('Mariana Souza', 'mariana.souza@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81991234567', '2000-07-08', 'https://example.com/photos/mariana.jpg', 'FEMALE', 'Designer apaixonada por criar experiências visuais incríveis.', 1, 1);
INSERT INTO tb_role(authority) VALUES ('ROLE_CLIENT');
INSERT INTO tb_role(authority) VALUES ('ROLE_ADMIN');
insert into tb_user_role(user_id, role_id) VALUES(1,1);
insert into tb_user_role(user_id, role_id) VALUES(1,2);
insert into tb_user_role(user_id, role_id) VALUES(2,1);
insert into tb_user_role(user_id, role_id) VALUES(3,1);
INSERT INTO tb_article(title, content, url_photo, author_id) VALUES ('Segurança crianças', 'Crianças não devem usar internet sem um adulto', 'htto', 1);
INSERT INTO tb_article(title, content, url_photo, author_id) VALUES ('Segurança adolescente', 'Adolescentes não devem usar internet sem um adulto', 'htto', 2);
INSERT INTO tb_tutorial(title, content, author_id) VALUES('Jogos digitais', 'Jogos podem ser prejudicias as crianças', 1);
INSERT INTO tb_tutorial(title, content, author_id) VALUES('Cassinos digitais', 'Cassinos podem ser prejudicias as crianças', 2);
INSERT INTO tb_media(url) VALUES('https');
INSERT INTO tb_media(url) VALUES('http');
INSERT INTO tb_tutorial_media(tutorial_id, media_id) VALUES (1, 1);
INSERT INTO tb_tutorial_media(tutorial_id, media_id) VALUES (2, 2);
create table tb_article (author_id bigint, id bigserial not null, content text, title varchar(255), url_photo varchar(255), primary key (id));
create table tb_city (id bigserial not null, state_id bigint, name varchar(255), primary key (id));
create table tb_media (id bigserial not null, url varchar(255), primary key (id));
create table tb_role (id bigserial not null, authority varchar(255), primary key (id));
create table tb_state (id bigserial not null, name varchar(255) unique, primary key (id));
create table tb_tutorial (author_id bigint, id bigserial not null, content text, title varchar(255), primary key (id));
create table tb_tutorial_media (media_id bigint not null, tutorial_id bigint not null, primary key (media_id, tutorial_id));
create table tb_user (birth_day date, city_id bigint, id bigserial not null, state_id bigint, bio varchar(255), email varchar(255), gender varchar(255) check (gender in ('MALE','FEMALE','OTHERS')), name varchar(255), password varchar(255), phone varchar(255), url_photo varchar(255), primary key (id));
create table tb_user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));
alter table if exists tb_article add constraint FKi2770gm5tf8ghdmv8cqvlh2lk foreign key (author_id) references tb_user;
alter table if exists tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state;
alter table if exists tb_tutorial add constraint FKrk2cdvqdg2q5k797rya3h7mpm foreign key (author_id) references tb_user;
alter table if exists tb_tutorial_media add constraint FKg6pljbcmdm4scsry1u86lyswq foreign key (media_id) references tb_media;
alter table if exists tb_tutorial_media add constraint FK95rvnpl63nlvkhkdvgujy2dem foreign key (tutorial_id) references tb_tutorial;
alter table if exists tb_user add constraint FKinhks6mglno4yyrtj72ad3evj foreign key (city_id) references tb_city;
alter table if exists tb_user add constraint FKc6p1rfmndjmco6f9kaghn5ewh foreign key (state_id) references tb_state;
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_state(name) VALUES('pernambuco');
INSERT INTO tb_city(name, state_id) VALUES('recife', 1);
INSERT INTO tb_city(name, state_id) VALUES('jaboatão dos Guararapes', 1);
INSERT INTO tb_city(name, state_id) VALUES('olinda', 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('NaveGuard', 'navguard@navguard.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81987654321', '1998-05-15', 'https://example.com/photos/ana.jpg', 'FEMALE', 'Apaixonada por tecnologia e viagens.', 1, 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('Carlos Eduardo', 'carlos.edu@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81999887766', '1995-11-20', 'https://example.com/photos/carlos.jpg', 'MALE', 'Engenheiro de software com interesse em IA e startups.', 1, 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('Mariana Souza', 'mariana.souza@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81991234567', '2000-07-08', 'https://example.com/photos/mariana.jpg', 'FEMALE', 'Designer apaixonada por criar experiências visuais incríveis.', 1, 1);
INSERT INTO tb_role(authority) VALUES ('ROLE_CLIENT');
INSERT INTO tb_role(authority) VALUES ('ROLE_ADMIN');
insert into tb_user_role(user_id, role_id) VALUES(1,1);
insert into tb_user_role(user_id, role_id) VALUES(1,2);
insert into tb_user_role(user_id, role_id) VALUES(2,1);
insert into tb_user_role(user_id, role_id) VALUES(3,1);
INSERT INTO tb_article(title, content, url_photo, author_id) VALUES ('Segurança crianças', 'Crianças não devem usar internet sem um adulto', 'htto', 1);
INSERT INTO tb_article(title, content, url_photo, author_id) VALUES ('Segurança adolescente', 'Adolescentes não devem usar internet sem um adulto', 'htto', 2);
INSERT INTO tb_tutorial(title, content, author_id) VALUES('Jogos digitais', 'Jogos podem ser prejudicias as crianças', 1);
INSERT INTO tb_tutorial(title, content, author_id) VALUES('Cassinos digitais', 'Cassinos podem ser prejudicias as crianças', 2);
INSERT INTO tb_media(url) VALUES('https');
INSERT INTO tb_media(url) VALUES('http');
INSERT INTO tb_tutorial_media(tutorial_id, media_id) VALUES (1, 1);
INSERT INTO tb_tutorial_media(tutorial_id, media_id) VALUES (2, 2);
create table tb_article (author_id bigint, id bigserial not null, content text, title varchar(255), url_photo varchar(255), primary key (id));
create table tb_city (id bigserial not null, state_id bigint, name varchar(255), primary key (id));
create table tb_media (id bigserial not null, url varchar(255), primary key (id));
create table tb_role (id bigserial not null, authority varchar(255), primary key (id));
create table tb_state (id bigserial not null, name varchar(255) unique, primary key (id));
create table tb_tutorial (author_id bigint, id bigserial not null, content text, title varchar(255), primary key (id));
create table tb_tutorial_media (media_id bigint not null, tutorial_id bigint not null, primary key (media_id, tutorial_id));
create table tb_user (birth_day date, city_id bigint, id bigserial not null, state_id bigint, bio varchar(255), email varchar(255), gender varchar(255) check (gender in ('MALE','FEMALE','OTHERS')), name varchar(255), password varchar(255), phone varchar(255), url_photo varchar(255), primary key (id));
create table tb_user_role (role_id bigint not null, user_id bigint not null, primary key (role_id, user_id));
alter table if exists tb_article add constraint FKi2770gm5tf8ghdmv8cqvlh2lk foreign key (author_id) references tb_user;
alter table if exists tb_city add constraint FK1rn7oty4mwqviyw8vk67crapo foreign key (state_id) references tb_state;
alter table if exists tb_tutorial add constraint FKrk2cdvqdg2q5k797rya3h7mpm foreign key (author_id) references tb_user;
alter table if exists tb_tutorial_media add constraint FKg6pljbcmdm4scsry1u86lyswq foreign key (media_id) references tb_media;
alter table if exists tb_tutorial_media add constraint FK95rvnpl63nlvkhkdvgujy2dem foreign key (tutorial_id) references tb_tutorial;
alter table if exists tb_user add constraint FKinhks6mglno4yyrtj72ad3evj foreign key (city_id) references tb_city;
alter table if exists tb_user add constraint FKc6p1rfmndjmco6f9kaghn5ewh foreign key (state_id) references tb_state;
alter table if exists tb_user_role add constraint FKea2ootw6b6bb0xt3ptl28bymv foreign key (role_id) references tb_role;
alter table if exists tb_user_role add constraint FK7vn3h53d0tqdimm8cp45gc0kl foreign key (user_id) references tb_user;
INSERT INTO tb_state(name) VALUES('pernambuco');
INSERT INTO tb_city(name, state_id) VALUES('recife', 1);
INSERT INTO tb_city(name, state_id) VALUES('jaboatão dos Guararapes', 1);
INSERT INTO tb_city(name, state_id) VALUES('olinda', 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('NaveGuard', 'navguard@navguard.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81987654321', '1998-05-15', 'https://example.com/photos/ana.jpg', 'FEMALE', 'Apaixonada por tecnologia e viagens.', 1, 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('Carlos Eduardo', 'carlos.edu@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81999887766', '1995-11-20', 'https://example.com/photos/carlos.jpg', 'MALE', 'Engenheiro de software com interesse em IA e startups.', 1, 1);
INSERT INTO tb_user(name, email, password, phone, birth_day, url_photo, gender, bio, state_id, city_id) VALUES ('Mariana Souza', 'mariana.souza@example.com', '$2a$10$eACCYoNOHEqXve8aIWT8Nu3PkMXWBaOxJ9aORUYzfMQCbVBIhZ8tG', '81991234567', '2000-07-08', 'https://example.com/photos/mariana.jpg', 'FEMALE', 'Designer apaixonada por criar experiências visuais incríveis.', 1, 1);
INSERT INTO tb_role(authority) VALUES ('ROLE_CLIENT');
INSERT INTO tb_role(authority) VALUES ('ROLE_ADMIN');
insert into tb_user_role(user_id, role_id) VALUES(1,1);
insert into tb_user_role(user_id, role_id) VALUES(1,2);
insert into tb_user_role(user_id, role_id) VALUES(2,1);
insert into tb_user_role(user_id, role_id) VALUES(3,1);
INSERT INTO tb_article(title, content, url_photo, author_id) VALUES ('Segurança crianças', 'Crianças não devem usar internet sem um adulto', 'htto', 1);
INSERT INTO tb_article(title, content, url_photo, author_id) VALUES ('Segurança adolescente', 'Adolescentes não devem usar internet sem um adulto', 'htto', 2);
INSERT INTO tb_tutorial(title, content, author_id) VALUES('Jogos digitais', 'Jogos podem ser prejudicias as crianças', 1);
INSERT INTO tb_tutorial(title, content, author_id) VALUES('Cassinos digitais', 'Cassinos podem ser prejudicias as crianças', 2);
INSERT INTO tb_media(url) VALUES('https');
INSERT INTO tb_media(url) VALUES('http');
INSERT INTO tb_tutorial_media(tutorial_id, media_id) VALUES (1, 1);
INSERT INTO tb_tutorial_media(tutorial_id, media_id) VALUES (2, 2);
